### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by NicoHood** [elementary/switchboard-plug-keyboard#107]
@danrabbit @codygarver Hi, could you please add the missing tag for release 0.3.2?

It should be this commit:
https://github.com/elementary/switchboard-plug-keyboard/commit/81cd239e5df502cca00c50142237dbd23d835d33

As an alternative you could of course create a new tag/version.
Edit: The old tag does not compile on never vala versions, so it'd be nice if you can tag a new release please.

**Comment by danrabbit** [comment]
Closing this because a new release was tagged in June https://github.com/elementary/switchboard-plug-keyboard/releases/tag/0.3.3
