### ISSUE TITLE
Super+Space to switch input

### ISSUE THREAD

**Issue by alex285** [elementary/switchboard-plug-keyboard#120]
Super+Space is nowadays a common method to switch inputs, and it guarantees no conflicts with applications shortcuts. By default elementary is using Alt+Shift, and there is not an option for Super+Space

**Comment by png2378** [comment]
As far as I know, Alt+Shift is the most popular combination for switching keyboard layout, which is also used in other popular desktops (for example in GNOME, as well as in all versions of Windows that I remember).

Super+Space is used to launch the application menu (Slingshot), therefore I believe that this issue should be closed.

**Comment by alex285** [comment]
@png2378  GNOME 3.0 is using Super+Space since ever, it is Ubuntu that overrides it with Alt+Shift, but they changed that since 17.10 release

There are not "all Windows versions", there is a single one (Windows 10), and they use Super+Space

Also, on https://github.com/elementary/default-settings/issues/3 there is a discussion to bind Super for Slingshot

**Comment by png2378** [comment]
I don't use Ubuntu 17.10, but I just checked Windows 10 and layout switched via Win+Space and via Alt+Shift ("out of the box" both options works).

In Freya there was no technical opportunity to use Alt+Shift to switch layouts, this combination was [introduced](https://github.com/elementary/default-settings/commit/eecb37590bf5d71d7db5856dfeb27bd03ff0d555) since the Loki release. This decision was taken after discussion in dev's chat in Slack and I think it would be wrong to change the order of things in each ensuing release.

In any case, at the moment there is no way to reassign combination on Win+Space (if you know how to do this, please tell us). If it is technically possible, it will be correct to ask the community which option is more preferable.

**Comment by danrabbit** [comment]
I'm going to close this as "Design Conflict" since Super + Space is the applications menu shortcut

**Comment by pevzi** [comment]
> I'm going to close this as "Design Conflict" since Super + Space is the applications menu shortcut

Why not make the menu shortcut customizable then? As mentioned above, `super+space` is used for layout switching in Ubuntu and Windows by default, so I would expect it to be included as an option, at least. Not to mention that `alt+shift` traditionally conflicts with hotkeys in other applications thanks to a long-standing Xorg "feature".

**Comment by sryze** [comment]
I agree, there should be an option to use Super+Space as the shortcut for switching layouts. Given that the default app menu shortcut can be changed from Super+Space to something else I don't see a reason not to include Super+Space in the list of possible key combinations.

Also, using some other key combinations conflicts with other common shortcuts, for example

* Alt+Shift - if I use this combination I can't use Alt+Shift+Tab to switch apps backwards in the Alt+Tab menu
* Ctrl+Shift - if I use this one I can't use Ctl+Shift+V to paste text into the terminal

**Comment by OmarShawky1** [comment]
things in elementary OS are logical and i agree with the strategy but using universal/conventional shortcuts even if they where made wrong is perhaps necessary, for me using alt+shift is good but if conflicts with any shortcut that depends on alt+shift like in intellij, so i made a compromise to change them to the next universal shortcut which is super+space but after 2 days of work i couldn't make it work, so i hope to make things easier for users and much suitable for their legacy usage

**Comment by F-Yousri** [comment]
+1 here
just think of backward tab cycling (alt + shift + tab by default)  which doesn't work due to the layout switching shortcut.
Not to mention that people coming from ubuntu are used to using (super + space) for switching layouts.

**Comment by TicTac7x** [comment]
Imagine having to deal with this in 2021.

Here's my workaround that supports dynamically more than 2 layouts:
1. Remove `<Super>space` from panel-main-menu keybind: `$ gsettings set org.gnome.desktop.wm.keybindings panel-main-menu "[]"`
2. Set Windows key to open up the applications menu: `$ gsettings set org.pantheon.desktop.gala.behavior overlay-action "io.elementary.wingpanel --toggle-indicator=app-launcher"`
3. (Optional) Disable `Alt + Shift` from the keyboard settings
4. Add custom keybind with following command `/home/yourusername/.layout.sh`, set keybind as `Windows + Space` or whatever you like. (if you are not able to set the keybind you would like to, change it manually with `dconf-editor` by changing the following key: `org.gnome.settings-daemon.plugins.media-keys.custom-keybindings.custom0.binding`
5. Create `.layout.sh` file in your home folder with following content:
```shell
#!/bin/bash

declare -i sources=$(gsettings get org.gnome.desktop.input-sources sources | tr -cd '(' | wc -c)
declare -i current=$(gsettings get org.gnome.desktop.input-sources current | sed 's/uint32 //')
declare -i new=0

if [[ $((${sources} - 1)) > ${current} ]]; then
    new=$((current + 1))
fi

gsettings set org.gnome.desktop.input-sources current ${new}
```

**Comment by OmarShawky1** [comment]
> Imagine having to deal with this in 2021.
> 
> Here's my workaround that supports dynamically more than 2 layouts:
> 
> 1. Remove `<Super>space` from panel-main-menu keybind: `$ gsettings set org.gnome.desktop.wm.keybindings panel-main-menu "[]"`
> 2. Set Windows key to open up the applications menu: `$ gsettings set org.pantheon.desktop.gala.behavior overlay-action "io.elementary.wingpanel --toggle-indicator=app-launcher"`
> 3. (Optional) Disable `Alt + Shift` from the keyboard settings
> 4. Add custom keybind with following command `/home/yourusername/.layout.sh`, set keybind as `Windows + Space` or whatever you like. (if you are not able to set the keybind you would like to, change it manually with `dconf-editor` by changing the following key: `org.gnome.settings-daemon.plugins.media-keys.custom-keybindings.custom0.binding`
> 5. Create `.layout.sh` file in your home folder with following content:
> 
> ```shell
> #!/bin/bash
> 
> declare -i sources=$(gsettings get org.gnome.desktop.input-sources sources | tr -cd '(' | wc -c)
> declare -i current=$(gsettings get org.gnome.desktop.input-sources current | sed 's/uint32 //')
> declare -i new=0
> 
> if [[ $((${sources} - 1)) > ${current} ]]; then
>     new=$((current + 1))
> fi
> 
> gsettings set org.gnome.desktop.input-sources current ${new}
> ```

You really do not need to do all that to change the language, i found out the solution and it is quite simple, just using dconf, remove whatever is using your key shortcut and replace them. This is too much work for just changing language IMHO.
