### ISSUE TITLE
Command + T does not  open Terminal on daily ppa on loki

### ISSUE THREAD

**Issue by ho3ein-mola** [elementary/switchboard-plug-keyboard#155]
other shortcut seems to work fine.

**Comment by Djaler** [comment]
It does not work sometimes for me on Juno.

**Comment by Thalexander** [comment]
Might be due to the shortcut being set to the old binary name, whereas the RDNN efforts have changed that, you should be able to create a custom shortcut for 'io.elementary.terminal' and re-assign cmd-t to that.

**Comment by ho3ein-mola** [comment]
after making custom shortcut its work now.

**Comment by ho3ein-mola** [comment]
i hope we don't see this kind of things in final release . and thank's for support.
