### ISSUE TITLE
Allow "print screen" as compose key

### ISSUE THREAD

**Issue by rdebeasi** [elementary/switchboard-plug-keyboard#159]
According to [this post](https://medium.com/elementaryos/juno-progress-for-march-6fd2d553c237), allowed compose keys are:
- Caps Lock
- Right Alt
- Right Ctrl
- Right Super

Would it be possible to also add the print screen key to this list? On most ThinkPads, this key is on the bottom right between Ctrl and Alt ([photo](http://blog.lenovo.com/uploads/general/TopView_T430s_crop.jpg)). I prefer to use this as my compose key because it's easy to access and because re-mapping this key prevents me from accidentally taking screenshots when I reach for Ctrl or Alt. (It's also in the location where you might find Right Super on a larger keyboard.)

Thank you! :smile:

**Comment by cassidyjames** [comment]
I'm -1 on this since <kbd>Prt Sc</kbd> is a default shortcut for something else; this would require remapping and conflicting with an existing shortcut, which is a lot of extra logic and special casing for a key that I've never hear used like this before.

**Comment by rdebeasi** [comment]
Makes sense. Thanks for the quick reply!
