### ISSUE TITLE
Names of IBus input sources not shown

### ISSUE THREAD

**Issue by jlnr** [elementary/switchboard-plug-keyboard#173]
I've set up a fresh Juno VM in Traditional Chinese. Like Ubuntu 18.04, this gives the initial user both a QWERTY layout and the ibus-chewing IME. However, the name of the IBus source is not shown in the GUI:

<img width="798" alt="bildschirmfoto 2018-08-19 um 17 48 07" src="https://user-images.githubusercontent.com/70772/44310763-22655900-a3dc-11e8-884a-70c03da5aa91.png">

This is how g-c-c does it: https://gitlab.gnome.org/GNOME/gnome-control-center/blob/master/panels/region/cc-ibus-utils.c

Will hopefully send a PR in a bit.

**Comment by danrabbit** [comment]
Should be fixed now :)
