### ISSUE TITLE
Traditional layout switch shortcut?

### ISSUE THREAD

**Issue by WattanaGaming** [elementary/switchboard-plug-keyboard#182]
Having to press something like ALT + Caps Lock instead of Win + Space can decrease productivity as the user still needs some time to get used to the shortcut. Would be happy to use a more traditional shortcut like Win + Space

**Comment by peteruithoven** [comment]
Could you share why the current default layout switch shortcut <kbd>shift</kbd>+<kbd>tab</kbd> is uncommon? Maybe mention some distro's / os's that do this differently? 

> instead of Win + Space
But that's the default shortcut to open the Applications menu? Maybe I misunderstand?

Some relevant discussions:
https://github.com/elementary/switchboard-plug-keyboard/issues/120
https://github.com/elementary/default-settings/issues/4

**Comment by peteruithoven** [comment]
I'm closing this one. @WattanaGaming hasn't shared why <kbd>Win</kbd> + <kbd>Space</kbd> is common and <kbd>Alt</kbd> + <kbd>Caps Lock</kbd> is not our default.
