### ISSUE TITLE
Support alternative physical layout, "DVORAK" and variants. 

### ISSUE THREAD

**Issue by EliasGabrielsson** [elementary/switchboard-plug-keyboard#189]
I am missing support for DVORAK with the Swedish flavour SVORAK (http://aoeu.info/).
I notice that some language have variants like `German (Austria)` could it be a possibility to add for example: `English (Dvorak)` and `Swedish (Svorak)` or does it bring to much clutter?

Maybe have an "advance" dropdown menu which let you choose your keyboard layout (Dvorak, Colemak, Qwerty and so on...) and thereafter populate them with specific language as them are added.

I get it if this is not top priority in relation to userbase usage but this pushes the ergonomics of eOS forward so it must be a good thing in the mantra of being user friendly operative system.

**Comment by danrabbit** [comment]
It looks like Swedish Dvorak is available in the latest release :)
