### ISSUE TITLE
Expose typing delays from a11y

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-keyboard#191]
Probably need some descriptive copy mentioning what it does and to whom it may be useful—the current copy in a11y isn't the best in context, and outside the a11y context I think it could be confusing.

**Comment by danrabbit** [comment]
![Screenshot from 2020-01-17 15 21 28@2x](https://user-images.githubusercontent.com/7277719/72652792-12d5a100-393d-11ea-96da-c60ca6abaff7.png)

Does it make sense to have switches for each of these beeps? Should this instead be a combobox?
