### ISSUE TITLE
Multimedia buttons bindings are displayed as "Disabled"

### ISSUE THREAD

**Issue by Djaler** [elementary/switchboard-plug-keyboard#194]
There are many default multimedia keybindings: volume up-down, play/pause, etc. They are binded to fn+F(1-12). But they are displayed in settings as "Disabled"

![image](https://user-images.githubusercontent.com/7964583/48661636-3f1a3700-ea86-11e8-8235-8e3debbf2f94.png)
![image](https://user-images.githubusercontent.com/7964583/48661678-f616b280-ea86-11e8-98b1-115807ccefb2.png)

**Comment by knorquist** [comment]
I'm having the same issue, but not just that - it seems like these settings are actively fighting with me editing via `dconf-editor`. My volume media keys suddenly stopped working, so I fixed them via `dconf-editor` and everything was gravy until I updated today. Now they're broken, and no amount of trying to change it with `dconf-editor` will work.

Not just that, but trying to fix the keyboard shortcuts using the switchboard keyboard plug doesn't work either - when I click on something to edit, and then press the appropriate shortcut key, it deselects the shortcut and remains "Disabled".

![screenshot from 2018-11-28 15-54-40](https://user-images.githubusercontent.com/3306524/49190149-026ffa80-f326-11e8-8340-772775334ea5.png)

**Comment by Janiczek** [comment]
I have the same issue in the "Keyboard" switchboard (everything is `Disabled` and setting it through this app doesn't work, even actively makes it not work), but setting the values through `gsettings` makes it work again:

```
martin@juno ~ $ gsettings list-recursively | grep "media-keys volume"
org.gnome.settings-daemon.plugins.media-keys volume-mute 'XF86AudioMute'
org.gnome.settings-daemon.plugins.media-keys volume-up ''
org.gnome.settings-daemon.plugins.media-keys volume-down 'XF86AudioLowerVolume'
martin@juno ~ $ # "volume up" doesn't work
martin@juno ~ $ gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up 'XF86AudioRaiseVolume'
martin@juno ~ $ gsettings list-recursively | grep "media-keys volume"
org.gnome.settings-daemon.plugins.media-keys volume-mute 'XF86AudioMute'
org.gnome.settings-daemon.plugins.media-keys volume-up 'XF86AudioRaiseVolume'
org.gnome.settings-daemon.plugins.media-keys volume-down 'XF86AudioLowerVolume'
martin@juno ~ $ # "volume up" works again
```

**Comment by Zachs-Kappler** [comment]
I think all the shortcuts got disabled somehow. I can't even Super+T to bring up Terminal, but it isn't shown as disabled. My system is up-to-date as of yesterday, and this didn't happen until I restarted.

**Comment by zamber** [comment]
Same issue. Fixing it with dconf doesn't make a difference. 
[journalctl-output.txt](https://github.com/elementary/switchboard-plug-keyboard/files/4240477/journalctl-output.txt)
