### ISSUE TITLE
Allow different input method for each window

### ISSUE THREAD

**Issue by khongi** [elementary/switchboard-plug-keyboard#195]
![brcqbsv49sy11](https://user-images.githubusercontent.com/11983684/48702002-1615b580-ebf0-11e8-8776-a8c49122f601.png)
It would be useful if the input method for a window was remembered. This way the user who uses e.g German to write emails and English to code, wouldn't have to change the language every time switching between windows.

**Comment by lenemter** [comment]
Closing in favor of https://github.com/elementary/gala/issues/180.
