### ISSUE TITLE
How to set Ctrl+Space shortcut for keyboard layout switching?

### ISSUE THREAD

**Issue by svladykin** [elementary/switchboard-plug-keyboard#196]
I'm a Mac user and on Mac pretty much everything is done with `Cmd` key instead of `Ctrl`. 
Now I use Elementary with Mac keyboard and want to configure the OS to behave as close to my original setup as possible.

I was able to switch `Cmd` and `Ctrl` keys using GNOME Tweaks app and it works well, but I see no way to configure `Ctrl+Space` for keyboard layout switching, there is only `Alt+Space`:
https://github.com/elementary/switchboard-plug-keyboard/blob/master/src/Views/Layout.vala#L54
It would be great to add `Ctrl+Space` to this list.

Maybe there is a workaround for this issue for now? Probably I can put some string like `ctrl_space_toggle` to some config?

**Comment by peteruithoven** [comment]
Thanks for the report! I'm afraid this is a duplicate of #182
