### ISSUE TITLE
Spell out "Control" in to match other key names

### ISSUE THREAD

**Issue by waldyrious** [elementary/switchboard-plug-keyboard#203]
The options for overriding the Caps Lock key all use the spelled-out version of the keys ("Control" instead of "Ctrl", "Escape" instead of "Esc", etc.), but one of them uses the abbreviated "Ctrl":

https://github.com/elementary/switchboard-plug-keyboard/blob/d84c55240a2349c4b8546d7073adc9eaaeba0b49/src/Views/Layout.vala#L103

This is especially glaring since the other occurrence in the same list uses "Control":

https://github.com/elementary/switchboard-plug-keyboard/blob/d84c55240a2349c4b8546d7073adc9eaaeba0b49/src/Views/Layout.vala#L107

I would gladly submit a PR, but since that would edit a user-facing message (which is a key in dozens of `.po` files such as [this](https://github.com/elementary/switchboard-plug-keyboard/blob/5f04285d0e38bada5d2b1d50f1dad5fcba92070b/po/aa.po#L214)), I'm not sure if it's OK to change all those files in a PR or if some more elaborate syncing is needed to make the change work with Weblate. How should I proceed?

**Comment by cassidyjames** [comment]
@waldyrious a PR is fine, we can update the string templates and the Weblate will begin merging in new translations as they come in.
