### ISSUE TITLE
Elementary needs a default fullscreen shortcut.

### ISSUE THREAD

**Issue by Blast-City** [elementary/switchboard-plug-keyboard#206]
Hi.

I just found out that there is a lot of apps that don't use the traditional F11 to go to fullscreen, but instead use the "toggle fullscreen" (org.gnome.desktop.wm.keybindings toggle-fullscreen) to go to fullscreen mode.

Some of this apps are:
- Elementary Files
- Elementary Settings
- Simple Scan.
- Libreoffice.

Unfortunately, this shortcut is not activated by default and is not mentioned anywhere.

What if there was a Elementary default fullscreen shortcut that would be activated by default and would show on the keyboard shortcuts overlay? Something like `Super+Return`?

I think this would be a nice feature.

**Comment by jeremypw** [comment]
I am not sure full-screen makes much sense for apps like Files which make heavy use of the headerbar.  And it may interfere with the search window. Although I suppose most actions can be performed with keyboard shortcuts though.

There is already a system shortcut for 'toggle-maximise' (`<Super><UpArrow>`)

**Comment by Blast-City** [comment]
> I am not sure full-screen makes much sense for apps like Files which make heavy use of the headerbar. And it may interfere with the search window. Although I suppose most actions can be performed with keyboard shortcuts though.
> 
> There is already a system shortcut for 'toggle-maximise' (`<Super><UpArrow>`)

Hi.

That makes sense. Exiting fullscreen mode to use the toolbar on Apps that weren't made to work fullscreen is weird.

Maybe is better to leave the fullscreen option shortcut to the app developers instead of being OS based. On other hand every app would be able to be made fullscreen with an uniform shortcut.

I was just amazed at how well libreoffice worked with the toggle. Even the Elementary Photos image viewer worked like it should. [This issue was solver instantly](https://github.com/elementary/photos/issues/217)

**Comment by jeremypw** [comment]
There are some apps, like screenshot, where it would make even less sense for fullscreen to be forced by the window manager, although I suppose the developer could block it.  For Files, the little bit of extra screen space from fullscreen over maximise would not make much difference anyway.

**Comment by Blast-City** [comment]
Maybe it's better to close this issue.  

I guess that the "toggle fullscreen" is sort of a brute force way of putting an app in fullscreen mode.

It's better to let app devs choose which is the shortcut or if that app should be put in fullscreen mode in the first place.

Thanks.
