### ISSUE TITLE
Missing default keyboard shortcuts for common, pre-installed apps

### ISSUE THREAD

**Issue by uncertainquark** [elementary/switchboard-plug-keyboard#208]
Many common pre-installed apps are missing keyboard shortcuts.
![screenshot from 2019-02-27 07-21-01](https://user-images.githubusercontent.com/22585732/53480392-21a33300-3aa1-11e9-8dc2-666c19452e0d.png)

Files app, for instance, could use something like `Super+E`, which is what opens the file manager on Windows.

**Comment by uncertainquark** [comment]
Any thoughts on this? Recently, KDE also added a quick file manager shortcut for the Plasma desktop.

**Comment by danrabbit** [comment]
Closing as a duplicate of #19
