### ISSUE TITLE
Home Folder entry should be replaced by "Files"

### ISSUE THREAD

**Issue by moonmehta** [elementary/switchboard-plug-keyboard#215]
When assigning a shortcut to open the default entry "Home Folder", it works but doesn't remember the last state of the Files app, which is what is expected in elementary OS. Replace Home Folder with the Files app instead.

![Screenshot from 2019-05-14 18-27-07](https://user-images.githubusercontent.com/22585732/57699749-114d2e00-7676-11e9-969b-3ee789b44bab.png)

**Comment by uncertainquark** [comment]
#208 is not the same issue but is related.

**Comment by peteruithoven** [comment]
Shouldn't these shortcuts be app agnostic though? Like the same shortcut should still handle the files handling app, even when the default files handling app is changed.

**Comment by uncertainquark** [comment]
Yes, true. In that case, should rename it to "File Manager"? Also, what to do about this? 

> Home folder shortcut doesn't restore last app state?

Does this still belong here?

**Comment by lenemter** [comment]
Closing in favor of https://github.com/elementary/switchboard-plug-keyboard/issues/74.
