### ISSUE TITLE
Command + P to open display settings

### ISSUE THREAD

**Issue by SaulNunez** [elementary/switchboard-plug-keyboard#216]
I've switched to Elementary OS and noted Command + P doesn't open display settings like in KDE or Windows. And in my cursory search I haven't found a way, but it would be nice to have a entry for a shortcut with Command + P as a default if you end up using projectors or secondary displays once in a while.

**Comment by lenemter** [comment]
Closing in favor of https://github.com/elementary/gala/issues/109
