### ISSUE TITLE
Some keyboard buttons aren't working

### ISSUE THREAD

**Issue by mkniloy** [elementary/switchboard-plug-keyboard#245]
Some buttons (like q,w,o,p) aren't working

**Comment by kgrubb** [comment]
Hey @mkniloy can you elaborate on when this is happening? Are your keys always non-functional, or is it only in certain situations?

**Comment by mkniloy** [comment]
They are always non functional. It was fixed on a recent update...but the problem came back again..

**Comment by santileortiz** [comment]
Which kind of keyboard do you have?, Which keyboard layout/language do you use?

Could you do the following to check that events are actually getting to the system?

1) Install evtest by running this on a terminal
`$ sudo apt-get install evtest`

2) Then run it on a terminal, choose your device from the list and press the keys that aren't working. Use the following command for that:
`$ sudo evtest`

**Comment by mkniloy** [comment]
> Which kind of keyboard do you have?, Which keyboard layout/language do you use?
> 
> Could you do the following to check that events are actually getting to the system?
> 
> 1. Install evtest by running this on a terminal
>    `$ sudo apt-get install evtest`
> 2. Then run it on a terminal, choose your device from the list and press the keys that aren't working. Use the following command for that:
>    `$ sudo evtest`

I don't thik I understood your 2nd point...(I'm new on linux)

**Comment by mkniloy** [comment]
The problem is resolved
