### ISSUE TITLE
can't type single character twice, quickly

### ISSUE THREAD

**Issue by SkyHook42** [elementary/switchboard-plug-keyboard#255]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Long version:
<https://elementaryos.stackexchange.com/questions/20950/can-t-type-single-character-twice-quickly>: can't create link Safari 11.1.2

### To Reproduce
See previous link.
Can't reproduce, had to wipe the drive. Current OS install working but afraid to touch Keyboard Behaviour adjustments. 

### Expected behavior
Keyboard behaviours in settings stopped aligning with actual behaviour. Bad behaviour unrecoverable. No workaround discovered. 

### Screenshots or screen recordings
NA

### Logs
NA

## Platform Information
- Elementary OS - last system update approximately 2019-10-12
- currently behaving reinstall approximately 2019-10-15
- Juno/Pantheon
- Dell Latitude D830 4GB/480GB SSD upgrades

Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
After that weekend, WiFi also failed and I decided to wipe and start fresh. Too ignorant to know what to delete in the file system, to test default settings refresh. My fresh wipe has a manually added and proven working Broadcomm WiFi driver (as did the first install), but the keyboard behaviour remains as per dist defaults.

**Comment by SkyHook42** [comment]
Link is working.

**Comment by lenemter** [comment]
Closing because reporter didn't provide sufficient information and the link doesn't work anymore. if you still encounter this issue, please file a separate issue.
