### ISSUE TITLE
Alt is always being intercepted by the OS

### ISSUE THREAD

**Issue by aidenlangley** [elementary/switchboard-plug-keyboard#270]
Hey

I have been trying to configure a particular shortcut in VS Code, `shift+alt+F` to format a document and have discovered Elementary OS is always intercepting `alt`. VS Code has a setting to disable this functionality called `window.enableMenuBarMnemonics` but it doesn't seem to be working, which leads me to believe Elementary OS is preventing it from working. 

If you try to replicate the issue you'll notice that even with the setting set to false, `File` will still be highlighted when you hit the alt key.

Appreciate any assistance, hopefully I'm on the right track.

Cheers

**Comment by cassidyjames** [comment]
Do you have an Alt key set as a Compose key in the System Settings?

**Comment by aidenlangley** [comment]
No, compose key is disabled for me.

**Comment by erasebegin** [comment]
Hi, having the exact same issue. Any news on this? Is there something I can change in Elementary to allow the use of alt+shift+k in vscode shortcuts?

**Comment by jeremypw** [comment]
This might be caused by Gala intercepting the change layout shortcut (default `Alt + Shift`)?  You could try changing the "Switch Layout" shortcut to something else.
