### ISSUE TITLE
Build failure with 2.3.6 on Arch Linux

### ISSUE THREAD

**Issue by alucryd** [elementary/switchboard-plug-keyboard#277]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Release 2.3.6 fails to build on Arch Linux.

### Logs
https://buildbot.alucryd.xyz/#/builders/100/builds/1/steps/7/logs/stdio

## Platform Information
- OS: Arch Linux
- vala: 0.48.2
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by ryonakano** [comment]
According to the log, you actually seemed to build 2.3.5, which does not include [this fix](https://github.com/elementary/switchboard-plug-keyboard/commit/28fa960f607f0b1d67f2864965a079bdfc23e3a8). 2.3.6 includes this change which should pass build against the latest version of valac.

**Comment by alucryd** [comment]
Right, revision hash wasn't updated on my end, thanks!
