### ISSUE TITLE
xkb-data-i18n no longer exists in Focal/Odin

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-keyboard#284]
It looks like the files it provided are now part of the lang packs: https://packages.ubuntu.com/search?searchon=contents&keywords=xkeyboard-config.mo&mode=exactfilename&suite=focal&arch=any

**Comment by tintou** [comment]
That means that we can stop depending on it on Focal as it is now in the language packs that are handled by switchboard-plug-locale
