### ISSUE TITLE
Elementary settings won't launch with keyboard installed

### ISSUE THREAD

**Issue by simonv74** [elementary/switchboard-plug-keyboard#315]
I can only open settings by uninstalling this module.

**Comment by davidmhewitt** [comment]
To be clear, you're saying "System Settings" (Switchboard), won't open if the package `switchboard-plug-keyboard` is installed?

If so, can you install `switchboard-plug-keyboard` again, and try opening switchboard from the terminal with the command:

```
io.elementary.switchboard
```

**Comment by simonv74** [comment]
Hi,

Yes, system settings will not launch with keyboard installed, I had to painstakingly uninstall each package one by one to get system settings to launch. Ironically, the setting I actually need to change is a keyboard one...

Anyway, I reinstalled it via terminal, and went to launch Switchboard and this error appeared:

(io.elementary.switchboard:7498): GLib-GIO-ERROR **: 10:28:03.033: Settings schema 'org.freedesktop.ibus.general' is not installed

**Comment by simonv74** [comment]
With keyboard uninstalled this error appears:

(io.elementary.switchboard:7939): Gtk-CRITICAL **: 10:33:35.669: gtk_entry_get_text: assertion 'GTK_IS_ENTRY (entry)' failed

Though settings app launches as expected.

**Comment by davidmhewitt** [comment]
Thanks, the first error is helpful, the second is harmless, as you say it launches anyway.

Do you happen to remember if you would have uninstalled `ibus` for any reason?

I _think_ if you install `ibus` with `sudo apt install ibus`, then the keyboard settings should work.

**Comment by simonv74** [comment]
Thanks very much, installing ibus got settings to launch again.

I've definitely never removed ibus at any point (until today, I'd never heard of it!)

**Comment by davidmhewitt** [comment]
Not sure what's happened there then. Thanks for the report though!

I'll leave this issue report open for now because we'll make sure that this module depends on `ibus` so it's less likely to get removed by accident.

**Comment by davidmhewitt** [comment]
We've made some changes that make this settings plug depend on `ibus`, in theory making it harder for it to get accidentally removed, so I'll close this issue now.

Thanks again for reporting it!
