### ISSUE TITLE
Keyboard Shortcuts 'disabled', and cannot be changed.

### ISSUE THREAD

**Issue by SudoCat01** [elementary/switchboard-plug-keyboard#317]
Hello,
Whenever I open the System Settings app and go to the 'shortcuts' tab under 'keyboard',
I am presented with the list of keyboard shortcuts, however across from each shortcut
it says 'disabled'. I can click it and enter a new string of key-presses, however it will
just go back to displaying 'disabled' across each option.
Strangely, the default keybindings still seem to work, they just can't be customized.

Here's a screenshot.

![Screenshot from 2020-08-22 23-30-50](https://user-images.githubusercontent.com/40328101/90970486-af63b100-e4d3-11ea-81b7-d1895a0efe86.png)

- Braelin Michelus (SudoCat01)

**Comment by bryanso** [comment]
This happens right after clicking update for Keyboard 2.3.6.
See my before and after comparison screens at 
https://elementaryos.stackexchange.com/questions/25547/very-serious-keyboard-app-bug-shortcuts-disabled

**Comment by ryonakano** [comment]
Seems like a regression of 60d2a4d
