### ISSUE TITLE
Obvious Option to disable "Keybord Shortcuts" help screen

### ISSUE THREAD

**Issue by luki9100** [elementary/switchboard-plug-keyboard#320]
I did not find an Option to disable the "Keyboard Shortcuts" help screen, which is on the super key by default. It is annoying, because I use the super key for other shortcuts and everytime I miss a key for my shortcuts the help pops up.

**Comment by danrabbit** [comment]
On the layout tab, there is an option "⌘ key behavior" that is set by default to "Shortcut Overlay". You can change this to either "Disabled" or to the show Applications menu
