### ISSUE TITLE
Kazakh Input Method

### ISSUE THREAD

**Issue by EpsilonKu** [elementary/switchboard-plug-keyboard#331]
![Screenshot from 2020-10-30 16-29-06](https://user-images.githubusercontent.com/63652620/97694612-c0fca280-1a9a-11eb-9f53-1f0839faf4f6.png)

There is only Kazakh(Arabic) Input Method. But nowadays we use Cyrillic, also government is planning to switch Latin 

## Platform Information
Elementary OS 6 - last update (30.10.20).
![Screenshot from 2020-10-30 16-27-13](https://user-images.githubusercontent.com/63652620/97694471-85fa6f00-1a9a-11eb-9d4e-a2020a467a98.png)

**Comment by santileortiz** [comment]
Which input method/layout are you trying to use?.

**Comment by EpsilonKu** [comment]
Kazakh with Cyrillic and Latin.

**Comment by lenemter** [comment]
Fixed in OS 7.1

![image](https://github.com/elementary/switchboard-plug-keyboard/assets/80143868/4f2924ff-9c3b-4747-b345-58bda833b095)
