### ISSUE TITLE
acessing different apps/documents (ALT+TAB)

### ISSUE THREAD

**Issue by ralxxx** [elementary/switchboard-plug-keyboard#340]
What I like about Elementary is that everything is simple and extremely intuitive. 
There only place where it is different: When it comes to switching between applications and documents.
- In Windows 10 the user can click easily (1-click) in the dock on an app or a document to open it. Alternatively, with ALT+TAB the user can switch easily between apps/documents.     
- In Gnome the doc is depending on what distro is being used, but the ALT+TAB feature is in a similar way easy. In particular with the option in the keyboard shortcuts to allow apps swapping or as an alternative windows swapping with ALT+TAB.   

All this in Elementary is so much more complicated. Accessing in the dock one out of several open documents (such as LibreOffice) requires first a right click before choosing. With ALT+TAB if 2 LibreOffice documents are open they are sometimes (but not all the time) shown as an option to chose from. If the user needs to swap often between 2 open text docs that annoying.   

document I feel in Elementary (5.1.7) it is hard and not intuitive at all the swap between different documents (for example 2 LibreOffice docs) or between two apps (for instance LibreOffice). Even more complicated it becomes when swapping between the Thunderbird man window and several open email messages. That's a hassle.

Expected behaviour
ALT+TAB. Allow at least in the keyboard shortcuts the option to swap between all open windows. While: When pressing ALT+TAB only once, that the last open window will be shown - the swap backward and forward between 2 apps/documents.

**Comment by danrabbit** [comment]
There's a discussion about the design of Alt + Tab that you can join here: https://github.com/elementary/gala/discussions/72

Closing this as a duplicate :)
