### ISSUE TITLE
XKB layouts incorrectly set as Ibus input methods in Hera

### ISSUE THREAD

**Issue by santileortiz** [elementary/switchboard-plug-keyboard#343]
The issue fixed by https://github.com/elementary/switchboard-plug-keyboard/pull/338 is present in a fresh install of elementary OS Hera.

## Steps to Reproduce

1. Go to System Settings > Keyboard > Layout
2. Try adding the Spanish (Latinamerica) layout, the default variant is fine, then make it the active layout.
3. Pressing the ; key in a US layout should get the ñ character, but it doesn't work.

The issue can be seen by opening dconf-editor and checking the value of `org.gnome.desktop.input-sources.sources`. The list should contain `('xkb','latam')` but instead it has `('ibus', 'latam')`.

**Comment by lenemter** [comment]
Fixed in #338, but hasn't been released at the time of filing this issue.
