### ISSUE TITLE
KEYBOARD

### ISSUE THREAD

**Issue by igormachado** [elementary/switchboard-plug-keyboard#344]
AFTER LAST UPDATE ME KEYBOARD LAYOUT ENGLISH(US,ALT.INT) DOES NOT WORK WELL. EX:  ~a != ã  shift+~+a does not work and shift+^+e does not work too.

**Comment by santileortiz** [comment]
It may be related to #343. Are you using elementary OS Hera?.

Can you install dconf-editor (`sudo apt-get install dconf-editor`) and use it to navigate to `org.gnome.desktop.input-sources`. What's the value for the `sources` key?.

**Comment by lenemter** [comment]
Closing because the issue is old. If you still encounter it, please reply here.
