### ISSUE TITLE
Default keyboard settings conflict

### ISSUE THREAD

**Issue by ayoungethan** [elementary/switchboard-plug-keyboard#345]
On a new install of Hera 5.1.7, the keyboard settings default to using alt+shift to change keyboard layout, which conflicts with alt+shift+tab to cycle through open windows in reverse. As a result, attempts to cycle through windows in reverse fail and produce unexpected behavior. Changing the keyboard layout hot key (e.g. to "both shift keys together") fixes the issue.

**Comment by lenemter** [comment]
Closing in favor of https://github.com/elementary/gala/issues/1261.
