### ISSUE TITLE
Quando tira a usb  e coloca novamente ele não digita mais

### ISSUE THREAD

**Issue by luanmarcosfgns** [elementary/switchboard-plug-keyboard#352]
Ao remover o meu teclado do meu notebook e reinseri-lo precisei de finalizar meu usuário para que o teclado volte a funcionar.

**Comment by meisenzahl** [comment]
@luanmarcosfgns please create issues in English.

## machine translated

When removing my keyboard from my notebook and reinserting it, I needed to terminate my user to get the keyboard working again.

**Comment by luanmarcosfgns** [comment]
Hello, when you remove the USB from the notebook keyboard with elementary OS it does not allow typing.

**Comment by luanmarcosfgns** [comment]
When you remove the USB from the notebook keyboard with elementary OS it does not allow typing

**Comment by luanmarcosfgns** [comment]
resolved with the command: sudo dpkg-reconfigure keyboard-configuration;
I changed the keyboard from generic 105 to microsoft keyboard
