### ISSUE TITLE
Shortcut TreeView not rendering properly when assigning shortcuts

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/switchboard-plug-keyboard#357]
## What Happened

![Screenshot from 2021-04-20 21 18 32](https://user-images.githubusercontent.com/31680656/115402483-05812380-a21e-11eb-91d2-6611393245a4.png)

## Expected Behavior

It should not render two texts

## Steps to Reproduce

1. Settings -> Keyboard -> Shortcuts
2. Assign a shortcut.

## Platform Information

eOS6, master switchboard-plug-keyboard

**Comment by pongloongyeat** [comment]
This seems fine on Adwaita

**Comment by danirabbit** [comment]
This was all completely rewritten so it's fixed now :)
