### ISSUE TITLE
In Chinese - Intelligent Pinyin, the first option has same text & highlight color

### ISSUE THREAD

**Issue by louis993546** [elementary/switchboard-plug-keyboard#359]
## What Happened
In the "Chinese - Intelligent Pinyin" IME, the first selection is blacked out in elementary OS 6 Beta
(I am not familiar with how this all works, so if this is not the right repo to report this issue, feel free to close it.)

## Expected Behavior
The first option is highlighted but still visible

## Steps to Reproduce

![Screenshot from 2021-05-01 10-42-52](https://user-images.githubusercontent.com/3873011/116776742-81733b00-aa6a-11eb-9956-4924ea820cb6.png)

1. Add "Chinese - Intelligent Pinyin"
1. Focus in the test strip
1. Start typing (e.g. "nihao")

## Platform Information
elementary OS 6 Beta
![Screenshot from 2021-05-01 10-49-10](https://user-images.githubusercontent.com/3873011/116776816-e0d14b00-aa6a-11eb-8ad7-f9e4d2554069.png)

**Comment by ryonakano** [comment]
Thank you for your report, I can also confirm this. However I guess this is not a issue of Keyboard Plug; maybe a stylesheet issue instead. Waiting for someone who has access to the stylesheet repo transferring this issue.

**Comment by jeremypw** [comment]
I have now raised an issue here: https://github.com/elementary/stylesheet/issues/1067

**Comment by ryonakano** [comment]
Closing in favor of https://github.com/elementary/stylesheet/issues/1067.
