### ISSUE TITLE
Not possible to create custom keyboard shortcut when the keyboard shortcut window is open directly from the main menu (for non-US layouts) 

### ISSUE THREAD

**Issue by remalhaut** [elementary/switchboard-plug-keyboard#361]
## What Happened
When creating a custom keyboard, clicking the "+" button creates a temporary entry. However, when I attempt to type in a command, the search box is activated instead and the temporary entry is lost. This happens even if previously selecting the temporary entry via mouse.
EDIT: This was for the UK keyboard layout. After adding the US layout and switching to it, it is now possible to add new shortcuts and edit them. When I switch back to the original layout, I can edit the existing shortcuts, but still cannot add new shortcuts.
EDIT 2: I just realized this only happens when I access the Keyboard Shortcuts window directly through the main menu. When I start with the System Settings window, the GTK search bar is greyed out and doesn't interfere with the command entry.

## Expected Behavior
The text typed in should show up in the dialog box that reads "Enter Command".

## Steps to Reproduce
0. Begin with a non-US keyboard layout (I tried UK and PT).
1. Open the Keyboard Shortcuts window directly through the main menu. Notice the search box is active.
![image](https://user-images.githubusercontent.com/7920835/117149717-5f9def00-adaf-11eb-9a84-b39f56632f83.png)
2. Select "Custom" in the sidebar.
3. Click "+" to create a new custom keyboard shortcut.
4. Type in the new command. This activates the search box and the new entry is lost.
5. Add the generic US keyboard layout and switch to it.
6. Try to add a new custom keyboard layout. It can now be added as expected.
7. Switch back to layout of choice. New shortcuts work and can be edited, but it still isn't possible to add new shortcuts.
8. Open the main System Settings window via the main menu. Select the Keyboard plug. Notice the search box is now greyed out.
![image](https://user-images.githubusercontent.com/7920835/117150467-1601d400-adb0-11eb-99ca-70b1183cf049.png)
9. Custom keyboard shortcut creation now works as expected.

## Platform Information
* Elementary OS 6 beta 1 (Linux 5.8.0-50-generic), recently installed.
switchboard-plug-keyboard version 2.4.1+r1358+pkg988daily~ubuntu6.1

**Comment by jeremypw** [comment]
I am not getting this issue on elementary 6.0 daily.  Please could you give details to which version of elementary you are using.

**Comment by remalhaut** [comment]
I just tried changing the keyboard layout from English (UK) to English (US), and the bug's gone!
This is on the beta + updates (uname -a: Linux h3x 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux). 
switchboard-plug-keyboard version 2.4.1+r1358+pkg988~daily~ubuntu6.1

**Comment by jeremypw** [comment]
I am using a default UK English keyboard layout without experiencing this issue. Same plug version. Also tried Portuguese layout with problem.

**Comment by remalhaut** [comment]
I just tried reinstalling the beta and updating everything through the Appcenter and I still get the same problem. Should I be installing the daily instead?

**Comment by jeremypw** [comment]
I just noticed that if you select an existing custom command with the keyboard, not by clicking on it, then it does not enter edit mode. The row is just highlighted. If the row is not in edit-mode (i.e. an entry box appears with the cursor in it) then typing on the keyboard does open the Gtk searchbox associated with the widget.  (I was thinking you were referring to the search box in the headerbar).  Is this what is happening to you? You must click on the name part of the command row (not the shortcut button) in order to edit it.

**Comment by jeremypw** [comment]
The Gtk searchbox is used for searching for a particular row in the view.  I am not sure it actually useful in this case as you are unlikely to have enough custom command rows to required search assistance.  Maybe we should disable it and switch to edit-mode automatically if you start typing.

**Comment by jeremypw** [comment]
I seem to remember that there was a bug in Files where switching layouts in the middle of an file rename caused the entry to lose focus and close.  It should not happen if you are just typing normal character with an XKB layout though.

**Comment by jeremypw** [comment]
You can demonstrate this by starting to edit a custom command and then press `<Alt><Shift>` or `<Shift><RightShift>` to switch to another layout. The edit will end and subsequent characters will be treated as a row search request.

**Comment by jeremypw** [comment]
There is a combobox under `SystemSettings/Keyboard/Layout` where can disable keyboard layout switching or choose a combination that it is less easy to hit accidentally.

**Comment by remalhaut** [comment]
Well, this is extremely weird: I tried adding a new shortcut again but I noticed this time the GTK search box was disabled transitioning from the main settings window to the keyboard settings window. Now everything works as expected and I'm doubting my sanity. Let me know, devs: should I leave this open or close the issue?

**Comment by remalhaut** [comment]
OK, after logging out and back in, I think I've figured it out:

- Opening the keyboard shortcuts window directly from the main menu, the GTK search bar is active and intercepts typing into the shortcut command entry (except if using the US layout, for some reason)
![image](https://user-images.githubusercontent.com/7920835/117149717-5f9def00-adaf-11eb-9a84-b39f56632f83.png)

- Opening the exact same window by starting at the system settings window and clicking "Keyboard", the GTK search bar is now greyed out, and is not activated when typing in a command.

![image](https://user-images.githubusercontent.com/7920835/117150467-1601d400-adb0-11eb-99ca-70b1183cf049.png)

**Comment by jeremypw** [comment]
Well spotted! I always open settings from the dock so I would never have seen that.  I think the best thing to do is close this and open a new more general issue against the switchboard repo as this bug affects all the plugs  (try search for "display" in Applications Menu and opening the display plug) so presumably is down to switchboard code.

**Comment by remalhaut** [comment]
On it, thanks for your help!
