### ISSUE TITLE
Text overlap in Switchboard --> Shortcuts --> Windows

### ISSUE THREAD

**Issue by candiedoperation** [elementary/switchboard-plug-keyboard#364]
## What Happened

 - **New Accelerator** text overlaps in Switchboard --> Shortcuts --> Windows
 - There is a **move design** cursor instead of a normal pointer
 - Mouse disabled until new accelerator or `esc` is pressed

## Expected Behavior

Behavior as usually in all other operating systems...

## Steps to Reproduce

1. Navigate to Switchboard --> Shortcuts --> Windows
2. Click something from the right-hand side list
3. Refer to **Picture-in-Picture in the below screenshot**

![Keyboard-Shortcuts-Issue](https://user-images.githubusercontent.com/47198395/120004111-057dfb80-bff4-11eb-8cf5-6040ce481b24.png)

### Logs

No Logs

## Platform Information

Operating System: elementary OS 6
Edition: (Public Beta)
Hardware Information:
- Quad-Core Intel® Core™ i5-8250U CPU @ 1.60GHz
- Intel® UHD Graphics 620 (Kabylake GT2)
- 7.7 GiB memory
- 467.2 GB storage (SSD)

Laptop Information: HP Pavilion x360

**Comment by jeremypw** [comment]
The first issue is a duplicate of #357 
Please open separate issues regarding the other points.

**Comment by candiedoperation** [comment]
Closing this issue, exact duplicate of Issue #357
