### ISSUE TITLE
Shortcuts bug

### ISSUE THREAD

**Issue by cbagur2** [elementary/switchboard-plug-keyboard#365]
Hi! When I tried to change the "minimize" shorcut setting, the system freeze totally, so I have to reset the notebook.
Regards, Carlos.

ASUS A53B

**Comment by stan-janssen** [comment]
Which shortcut are you trying to edit; is it the 'Unmaximize'? I cannot see 'Minimize' in the default list:

![shortcuts](https://user-images.githubusercontent.com/12174852/129482322-452120d9-9f20-4407-9667-b1f11d3d6d0f.png)
