### ISSUE TITLE
Shortcuts freeze, sometimes restart needed to fix.

### ISSUE THREAD

**Issue by sirsleon** [elementary/switchboard-plug-keyboard#378]
## What Happened

When creating a custom keyboard shortcut everything freezes.

## Expected Behavior

Able to create and edit keyboard shortcuts.

## Steps to Reproduce

1. Open System Settings > Keyboard
2. Select Shortcuts > Custom
3. Try creating/editing.

### Logs

n/a

## Platform Information

elementary OS 6
Up to date

**Comment by stan-janssen** [comment]
I'm not seeing this on a fresh install of elementaryOS 6. See example screen capture:


https://user-images.githubusercontent.com/12174852/129474737-82bbac01-6b17-44df-9228-ba74963f5e36.mp4


At what point does it look differently to you?

**Comment by sirsleon** [comment]
> I'm can't reproduce this on a fresh install of elementaryOS 6. See example screen capture:
> shortcuts.mp4
> 
> At what point does it look differently to you?

I didn't know thats how to create a shortcut sorry, the glitchy text made it confusing. I want to make my F9 key open settings, what command would I write?

**Comment by stan-janssen** [comment]
You'd write:

```
io.elementary.switchboard
```

as the command.

**Comment by sirsleon** [comment]
Thanks, one more thing, my F9 key is recognised as Tools which should open settings but it doesn't.

For the shortcut I had to make it Super + Tools if not it wouldn't work (Tools alone can't trigger settings even though it does everywhere else).

**Comment by stan-janssen** [comment]
That looks similar to the problem I'm having assigning the Brightness Up/Down keys by themselves, which does not work, while adding a modifier does work (#376).

**Comment by stan-janssen** [comment]
I also see what you meant by 'freeze'; while you're in the middle of assigning a shortcut key, you cannot click your way out of it to cancel the operation. The only way out is to press `Esc`, which I imagine is not at all obvious to everyone.

**Comment by stan-janssen** [comment]
I have a solution for your specific problem; see https://github.com/elementary/switchboard-plug-keyboard/issues/376#issuecomment-899068830.
