### ISSUE TITLE
IBus Daemon does not start automatically at login

### ISSUE THREAD

**Issue by kdwk** [elementary/switchboard-plug-keyboard#379]
## What Happened

Even when the user has set 2 or more input methods, and the IBus Daemon has to start at login to provide that function, it does not do so automatically. Instead, the user has to enter `ibus-daemon -d` in 'System Settings-> Applications-> Startup' to get it to work.

## Expected Behavior

When the user has more than 1 input method configured, `ibus-daemon -d` should be run automatically at startup, or equivalent solutions to the same effect

## Steps to Reproduce

1.
2.
3.

**Comment by jeremypw** [comment]
PR #374 aims to fix this - the same issue was raised in the wingpanel repo but it was better to fix it here.
