### ISSUE TITLE
Add text navigation shortcuts as customization options

### ISSUE THREAD

**Issue by mpanhans** [elementary/switchboard-plug-keyboard#386]
## Problem
Many users find text navigation keyboard shortcuts essential, and being able to customize them easily is important. Specifically I mean keyboard shortcuts for \<go to end of line>, \<go to end of line and select text>, \<move word left>, etc.

For users coming from MacOS in particular, they may feel much more comfortable if they can map these text navigation shortcuts to what their muscle memory is used to. This question has been raised in the [elementary OS Stack Exchange](https://elementaryos.stackexchange.com/questions/28619/how-to-get-cursor-text-navigation-like-macos-cmdctrl-for-end-start-of-line).

In addition, some keyboards such as those on Apple laptops do not have the \<home> and \<end> keys, making it impossible to use the beginning and end of line and associated keyboard shortcuts without customization options. 

These changes can be readily made with external plugins such as Autokey. But it would fit very nicely to be able to customize these shortcuts in the System Settings > Keyboard > Shortcuts tab.

## Proposal

In System Settings > Keyboard > Shortcuts, add the following eight commands as customizable:
\<go to end of line>
\<go to end of line and select text>
\<go to beginning of line>
\<go to beginning of line and select text>
\<move word left>
\<move word left and select text>
\<move word right>
\<move word right and select text>

**Comment by lenemter** [comment]
I'll close this because this is impossible. We don't have any control over these shortcuts. UI toolkits implement them themselves without involving the OS.
