### ISSUE TITLE
Shortcut key label not disappearing when reassigning shortcut

### ISSUE THREAD

**Issue by joeljosedev** [elementary/switchboard-plug-keyboard#395]
### What Happened?

When a shortcut is being reassigned to another key, the current shortcut key is still visible and the label to enter a new shortcut overlaps with it.

![Keyboard Shortcut bug](https://user-images.githubusercontent.com/53969297/148808467-7f18a21c-c28e-4674-b595-ea953b7d0ee1.png)

### Steps to Reproduce

1. Open the **System Settings** app.
2. Go to the Keyboard page
3. Navigate to the Shortcuts tab.
4. Click on a shortcut to assign a new shortcut.

### Expected Behavior

The name of the old shortcut should disappear when the user is reassigning the shortcut.

### OS Version

6.1 (Jólnir)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
Fixed in OS 7.
