### ISSUE TITLE
Caps Lock Key Remapping Stopped Working

### ISSUE THREAD

**Issue by anthonylei** [elementary/switchboard-plug-keyboard#402]
### What Happened?

There are two issues related Caps Lock Key Behavior Remapping:
- Before late March update: Need to reset the Caps Lock mapping every restart of OS.
- After later March update: Caps Lock mapping has stop working, that is Caps Lock key behavior does not map to the specified behavior including (as Ctrl or disable, etc). It only act as default Caps Lock key.

### Steps to Reproduce

1. Open Settings
2. Go to Keyboard
3. Change Caps Lock Behavior to "as Ctrl"

### Expected Behavior

Caps Lock key should behavior as specified in the setting, in this example, should act as a Control key.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
N/A
```

### Hardware Info

The issue occurred on both:
- Build in Laptop keyboard (Lenovo)
- Bluetooth connected keyboard

**Comment by TimFH** [comment]
This also happened to me using an LG Gram Z990-R-AAS9U1 laptop right after installing two Elementary OS 7.0 updates and rebooting, also on March 27, 2023. In my case not only does the "Caps Lock behavior" setting do nothing, but neither does the "Compose key" setting (so I don't have a compose key anymore).

I hope someone at Elementary IO is paying attention!

**Comment by dwmckee** [comment]
Similar experience to TimFH: remapping was working on Horus in mid March 2023 and had stopped by early April when I accepted a pending update. Platform is a Dell Latitude-E7250-373473f3 laptop.

**Comment by dwmckee** [comment]
> Similar experience to TimFH: remapping was working on Horus in mid March 2023 and had stopped by early April when I accepted a pending update. Platform is a Dell Latitude-E7250-373473f3 laptop.

And after a recent update cycle it has resolved. Yeah.

**Comment by danirabbit** [comment]
@TimFH can you confirm the issue has been resolved for you as well? I believe this may have been fixed by a recent Gala update

**Comment by TimFH** [comment]
It has been resolved.

Thunderbird's Quick Filter has stopped working however; I know it's not supported but the problem might be in gala, as well, especially since the QS tab is clearly not interfacing with the mouse and keyboard the way it used to.

⁣Get TypeApp for Android ​

**Comment by danirabbit** [comment]
Glad to hear that. Can you please open a new issue report at GitHub.com/elementary/gala for the new issue you've described?

Closing this issue since two people said it was fixed
