### ISSUE TITLE
Swedish (Macintosh) layout has @ in wrong place

### ISSUE THREAD

**Issue by alfrednerstu** [elementary/switchboard-plug-keyboard#411]
### What Happened?

I just installed elementary OS 6.1 Jólnir and set it up with the keyboard layout 'Swedish (Macintosh)'.

Unfortunatly it has the @ character in the wrong place. Currently it's at option+* but it should be option+2.
Look at these keyboard layouts from Apple support. On the Danish and Norwegian keyboards the @ is at option+* but on the Swedish one it's at option+2.

I hope you can change/update it soon, thanks!

https://support.apple.com/library/content/dam/edam/applecare/images/en_US/keyboards/swedish_notebook.png

https://support.apple.com/library/content/dam/edam/applecare/images/en_US/keyboards/danish_notebook.png
https://support.apple.com/library/content/dam/edam/applecare/images/en_US/keyboards/norwegian_notebook.png

### Steps to Reproduce

I choose 'Swedish (Macintosh)' in the keyboard layout options and tried to write a @ character.

### Expected Behavior

I should be able to write a @ character by option+2.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

16" Macbook Pro (2019)

**Comment by tintou** [comment]
Hi there, we are using XKB which is a common component to every linux distribution out there, can you forward this issue to their issue tracker at: https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues
Thanks in advance!

**Comment by lenemter** [comment]
Closing because it's upstream issue. As said, please report it here: https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues
