### ISSUE TITLE
Crashes because of missing settings schema

### ISSUE THREAD

**Issue by aspizu** [elementary/switchboard-plug-keyboard#426]
### What Happened?

Switchboard crashes

### Steps to Reproduce

1. Open io.elementary.switchboard
2. Click on Keyboard

### Expected Behavior

Should not crash switchboard

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
(io.elementary.switchboard:____): GLib-GIO-ERROR **: __:__:__.___: Settings schema 'org.gnome.settings-daemon.plugins.media-keys' does not contain a key named 'terminal'
```

### Hardware Info

OS: Arch Linux

**Comment by slackernetuk** [comment]
The same issue on Slackware as well, by the way version 2.6.0 works fine. 

**Backstrace**
[switchboard-plug-keyboard-bt.txt](https://github.com/elementary/switchboard-plug-keyboard/files/10036695/switchboard-plug-keyboard-bt.txt)
