### ISSUE TITLE
Shortcut for changing layout doesn’t respect my system settings

### ISSUE THREAD

**Issue by abdumu** [elementary/switchboard-plug-keyboard#504]
I have two language layouts, I changed the shortcut to alt+space and it worked nicely while logged in, once it goes to Lock Screen and I try to log in again I have to use shift+alt and my default doesn't work.

Thanks for the wonderful and amazing work.

You guys rock!

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/greeter/pull/658
