### ISSUE TITLE
"Take a Screenshot of an Area" shortcut does not work

### ISSUE THREAD

**Issue by taehyounpark** [elementary/switchboard-plug-keyboard#81]
Neither the default Shift-PrtSc nor any other combinations I have tried (eg. Alt-PrtSc) does not work.

The keyboard combiations work fine for other shortcuts (eg. entire screenshot, window screenshot, etc.)

**Comment by AlexFBP** [comment]
I can confirm this, i guess (don't know how to propose a patch by inspection of the source) that the commands are misconfigured.

I created custom commands and reasigned (on the GUI->Custom) as follows:

```
screenshot-tool -r -c #Area shot to clipboard - Ctrl+PrntScr
screenshot-tool -r #Area shot to file (normal) - Shift+Ctrl+PrntScr
```

Also, if you want, i can share you the following that i also asigned to keyb combinations:

```
gnome-system-monitor #Launch system monitor (if installed) - shift+ctrl+esc
xkill #Kill a GUI<--->PID - shift+ctrl+del
```

**Comment by danrabbit** [comment]
As far as I can tell, this is working in Juno daily. Closing as "Incomplete"
