### ISSUE TITLE
Default keyboard shortcuts not launching app

### ISSUE THREAD

**Issue by GiltosMx** [elementary/switchboard-plug-keyboard#93]
![screenshot from 2017-08-18 07 22 45](https://user-images.githubusercontent.com/14275369/29458717-0ca86dda-83e6-11e7-82ce-03edb37f0123.png)
It probably has something to do with the terminal being renamed to `io.elementary.terminal`, files to `io.elementary.files` and scratch to `io.elementary.code`. The only shortcut that still works is cmd+space for the Applications Launcher.

**Comment by Philip-Scott** [comment]
Yup, can confirm. The shortcuts seem to still be pointing to the names prior the RDNN changes

**Comment by Janiczek** [comment]
I'd like to help with this, but don't know where to look and could use a kick in the right direction.

I have looked at `src/Shortcuts/List.vala` and I see the `terminal` key there, but I don't know how that gets changed to either `pantheon-terminal` or `io.elementary.terminal`. Seems to me like it's going through some kind of "find default application" process?

**Comment by matzipan** [comment]
It appears that the change has been made [here ](http://bazaar.launchpad.net/~elementary-os/elementaryos/default-settings-loki/revision/230), but that there are a few pending packaging issues that need to be solved before this gets fixed.

**Comment by danrabbit** [comment]
Closing this issue as "Out of Scope" because it's an issue in https://github.com/elementary/default-settings (which should be fixed already)
